services:

  # PostgreSQL service
  postgresdb:
    image: postgres
    container_name: postgres-0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5332:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
